blueprint:
  name: Run actions when Garages Amsterdam data has a problem
  description: Run actions when a Garages Amsterdam data problem sensor turns on.
  domain: automation
  input:
    problem_sensor:
      name: Problem sensor
      selector:
        entity:
          filter:
            - integration: garages_amsterdam
              domain: binary_sensor
              device_class: problem
    actions:
      name: Actions
      selector:
        action:
triggers:
  - trigger: state
    entity_id: !input problem_sensor
    to: "on"
actions: !input actions
