blueprint:
  name: easyEnergy all-in current price
  description: >
    Create a template sensor that adds energy tax and purchase costs to the
    current easyEnergy electricity usage price.
  domain: template
  author: klaasnicolaas

  input:
    price_sensor:
      name: Current electricity usage price
      description: >
        Select the Current hour sensor on the easyEnergy
        Energy market price - Usage device. Its unit is EUR/kWh.
      selector:
        entity:
          filter:
            - integration: easyenergy
              domain: sensor

    energy_tax:
      name: Energy tax
      description: The energy tax to add in EUR/kWh.
      selector:
        number:
          mode: box
          step: 0.001
          unit_of_measurement: EUR/kWh

    purchase_costs:
      name: Purchase costs
      description: The purchase costs to add in EUR/kWh.
      selector:
        number:
          mode: box
          step: 0.001
          unit_of_measurement: EUR/kWh

variables:
  price_sensor: !input price_sensor
  energy_tax: !input energy_tax
  purchase_costs: !input purchase_costs

sensor:
  name: easyEnergy all-in current price
  unique_id: easyenergy_all_in_current_price
  icon: mdi:cash
  unit_of_measurement: "€/kWh"
  state_class: measurement
  state: >
    {% set current_price = states(price_sensor) | float(0) %}
    {{ (current_price + energy_tax + purchase_costs) | round(2) }}
