name: Documentation feedback
description: Provide feedback on a page on our website
body:
  - type: markdown
    attributes:
      value: |
        Thanks for opening an issue to provide feedback on our website/documentation.

        **Please note, this form is not for reporting bugs with running Home Assistant or its integrations.**
        Those bugs should be reported in the [Home Assistant Core issue tracker][core].

        [core]: https://github.com/home-assistant/core/issues
  - type: textarea
    attributes:
      label: Feedback
      description: >-
        Please be sure to provide feedback as clear as possible. Describe what
        you think is incorrect or can be improved, and try to provide a
        suggestion on how you think it can be improved or fixed.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Details
  - type: input
    id: url
    attributes:
      label: URL
      placeholder: "http://www.home-assistant.io/..."
      description: >
        A URL with a link to the page you are providing feedback for.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "e.g., 2022.7.0"
      description: >
        Latest stable version version of Home Assistant available
        (which does not have to match the version you are using).
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
