blueprint:
  name: Run actions at the EnergyZero lowest price time
  description: Run actions when the EnergyZero lowest-price timestamp for today is reached.
  domain: automation
  input:
    lowest_price_time_sensor:
      name: Lowest price time sensor
      selector:
        entity:
          filter:
            - integration: energyzero
              domain: sensor
              device_class: timestamp
    actions:
      name: Actions
      selector:
        action:
triggers:
  - trigger: time
    at: !input lowest_price_time_sensor
actions: !input actions
