name: home-assistant.io Test

on: [push, pull_request]

jobs:
  markdown-lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Check out files from GitHub
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setting up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20
          cache: "npm"
      - name: Check for .md files and suggest renaming
        run: |
          echo "Checking for .md files in source/_integrations..."
          MD_FILES=$(find source/_integrations -type f -name "*.md")
          if [ -n "$MD_FILES" ]; then
            echo "Found the following .md files:"
            echo "$MD_FILES"
            echo "⚠️ Please rename these files from .md to .markdown"
            exit 1
          fi
      - name: Install dependencies
        run: npm install
        env:
          CI: true
      - name: Run remark lint
        run: npm run markdown:lint
  textlint:
    name: Lint Text
    runs-on: ubuntu-latest
    steps:
      - name: Check out files from GitHub
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setting up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm install
        env:
          CI: true
      - name: Run textlint
        run: npm run textlint
